Repository pearlKinn/FESP01-JS-Project, pull requests merged in 2023-10, with the labels that each got.

#1 Feat: 할일 완료 여부 체크박스 추가
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
Labels: Feat

#3 TodoRegist 기능구현
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
  01.javascript/todoapp/package-lock.json
Labels: Feat

#4 Todo info
  01.javascript/todoapp/assets/js/pages/info/TodoInfo.js
Labels: Refactor

#5 Feat: 할일목록 수정
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
  01.javascript/todoapp/assets/js/pages/update/TodoUpdate.js
Labels: Feat

#6 Feat: 라우팅 적용
  01.javascript/todoapp/assets/js/App.js
  01.javascript/todoapp/assets/js/Router.js
  01.javascript/todoapp/assets/js/index.js
  01.javascript/todoapp/assets/js/pages/info/TodoInfo.js
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
  01.javascript/todoapp/assets/js/pages/update/TodoUpdate.js
  PPT/.DS_Store
  PPT/프로젝트 안내.pptx
Labels: Feat

#7 Style: log 삭제
  01.javascript/todoapp/assets/js/Router.js
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
Labels: Style

#8 Todo info
  01.javascript/todoapp/assets/css/index.css
  01.javascript/todoapp/assets/js/pages/info/TodoInfo.js
  01.javascript/todoapp/assets/js/pages/list/TodoList.js
  01.javascript/todoapp/assets/js/pages/regist/TodoRegist.js
  01.javascript/todoapp/assets/js/pages/update/TodoUpdate.js
  01.javascript/todoapp/index.html
Labels: fix, Style
